### ISSUE TITLE
Project/User Location

### ISSUE THREAD

**Issue by justinbesteman** [mainsite/selfstarted#104]
Research on Google Maps

**Comment by realzaidiguy** [comment]
Going with Google Maps is not going to be the right way to go because:

1) We only get 2500 geocoding lookups per day, after which it is 50cents per 1000 requests. If we start geocoding the user location, then start doing distance lookups from user to project or talent during searches, we're going to burn through our allotment very fast once we even begin to approach 100-ish users/projects..

2) The API is good in that it will convert pretty much any address, POI, city/state name, etc., loosely entered, all into lat/long, and will also give you a city name. However, you then end up with potentially one user entering a street address that identifies them in Winter Park, another ends up in Kissimmee, another ends up in Orlando, another in Ocoee, and now you're talking about a hairy mess confirming they're all local.

3) I think the better way to go, since we will likely roll this out slowly university by university is to hard code location options. Make location an array of 3 fields, for example: ['usa', 'florida', 'orlando area'], and have it be a drop down choice. Use this same format for users to fine tune the project location, but then also *STOP* pulling user location from linked-in, and instead make them enter it in their profile using this same type of drop down system. This will make matching users/projects significantly easier, and as time passes and we expand we can add on other locations, i.e., ['usa', 'florida', 'tampa area'], or ['canada', 'ontario', 'toronto area'], etc.

4) For area campuses, it would just be another location option, such as ["usa", "florida", "fort lauderdale area"] if for example UCF happened to have a campus there. Then later if we get a university in Ft Lauderdale, their location could work with the same options. For online courses, we could have a location like ['online', 'online', 'online']. or ['usa', 'online', 'online'] might be a better option to keep online within country boundary?

5) The issue is more classification so we can search, whether project or talent. Instead of array, it might be best to have 3 fields added to the users model: userCountry, userState, userCityArea, and the same for projects model: projectCountry, projectState, projectCityArea. When we all have time we can think it through together.
